include:
  - local: common/base.gitlab-ci.yml

variables:
  name: nodejs

playground:
  image: $image_under_test
  stage: test

  before_script:
    - pacman -Syuu --noconfirm git
    - git clone https://gitlab.com/opensavvy/playgrounds/gradle.git

  script:
    - cd gradle
    - ./gradlew jsNodeTest -PappGroup=just.a.test
